# Generated by Django 5.0.1 on 2025-09-21 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Broker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("broker_name", models.TextField()),
                ("broker_code", models.TextField(blank=True, null=True, unique=True)),
                ("broker_type", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "brokers",
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.TextField()),
                ("dba_name", models.TextField(blank=True, null=True)),
                ("tax_id", models.TextField(blank=True, null=True)),
                ("company_type", models.TextField(blank=True, null=True)),
                ("industry_code", models.TextField(blank=True, null=True)),
                ("industry_description", models.TextField(blank=True, null=True)),
                (
                    "annual_revenue",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("employee_count", models.IntegerField(blank=True, null=True)),
                ("website", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Companies",
                "db_table": "companies",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.TextField()),
                ("product_code", models.TextField(unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "products",
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_number",
                    models.TextField(blank=True, null=True, unique=True),
                ),
                ("submission_date", models.DateField(auto_now_add=True)),
                ("target_effective_date", models.DateField(blank=True, null=True)),
                (
                    "application_status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("in_progress", "In Progress"),
                            ("quoted", "Quoted"),
                            ("bound", "Bound"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="received",
                        max_length=20,
                    ),
                ),
                (
                    "estimated_premium",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "quoted_premium",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "bound_premium",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("underwriting_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "broker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.broker",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.company",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.product",
                    ),
                ),
            ],
            options={
                "db_table": "applications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quote_number", models.TextField(blank=True, null=True, unique=True)),
                ("quote_version", models.IntegerField(default=1)),
                ("quote_date", models.DateField(auto_now_add=True)),
                ("effective_date", models.DateField()),
                ("expiration_date", models.DateField()),
                (
                    "quote_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("presented", "Presented"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                            ("superseded", "Superseded"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("total_premium", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "commission_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("special_conditions", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.application",
                    ),
                ),
            ],
            options={
                "db_table": "quotes",
                "ordering": ["-created_at"],
            },
        ),
    ]
