# Generated by Django 5.2.6 on 2025-09-22 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('template_id', models.AutoField(primary_key=True, serialize=False)),
                ('template_name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('standard', 'Standard Certificate'), ('contractor', 'Contractor Certificate'), ('vendor', 'Vendor Certificate'), ('tenant', 'Tenant Certificate'), ('auto', 'Auto Certificate')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'certificate_templates',
            },
        ),
        migrations.RemoveField(
            model_name='application',
            name='id',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='id',
        ),
        migrations.AddField(
            model_name='application',
            name='application_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='broker',
            name='broker_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='company',
            name='company_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='product',
            name='coverage_type_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='product',
            name='venture_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='broker',
            field=models.ForeignKey(blank=True, db_column='broker_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.broker'),
        ),
        migrations.AlterField(
            model_name='application',
            name='company',
            field=models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='applications.company'),
        ),
        migrations.AlterField(
            model_name='application',
            name='product',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='applications.product'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='application',
            field=models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.CASCADE, to='applications.application'),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('certificate_id', models.AutoField(primary_key=True, serialize=False)),
                ('certificate_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('certificate_holder_name', models.CharField(max_length=255)),
                ('certificate_holder_address', models.TextField()),
                ('additional_insured_name', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_insured_address', models.TextField(blank=True, null=True)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('project_location', models.TextField(blank=True, null=True)),
                ('effective_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('certificate_status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('special_provisions', models.TextField(blank=True, null=True)),
                ('waiver_of_subrogation', models.BooleanField(default=False)),
                ('primary_and_noncontributory', models.BooleanField(default=False)),
                ('issued_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('quote', models.ForeignKey(db_column='quote_id', on_delete=django.db.models.deletion.CASCADE, to='applications.quote')),
                ('template', models.ForeignKey(db_column='template_id', on_delete=django.db.models.deletion.CASCADE, to='applications.certificatetemplate')),
            ],
            options={
                'db_table': 'certificates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificateCoverage',
            fields=[
                ('coverage_id', models.AutoField(primary_key=True, serialize=False)),
                ('coverage_type', models.CharField(choices=[('general_liability', 'General Liability'), ('auto_liability', 'Automobile Liability'), ('excess_umbrella', 'Excess/Umbrella Liability'), ('workers_comp', 'Workers Compensation'), ('property', 'Property'), ('professional', 'Professional Liability'), ('cyber', 'Cyber Liability'), ('other', 'Other')], max_length=30)),
                ('each_occurrence', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('general_aggregate', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('products_completed_ops', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('personal_advertising_injury', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('deductible', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('policy_number', models.CharField(blank=True, max_length=50, null=True)),
                ('policy_effective_date', models.DateField()),
                ('policy_expiration_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('certificate', models.ForeignKey(db_column='certificate_id', on_delete=django.db.models.deletion.CASCADE, to='applications.certificate')),
            ],
            options={
                'db_table': 'certificate_coverages',
            },
        ),
    ]
