# Generated by Django 5.2.6 on 2025-09-22 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_certificatetemplate_remove_application_id_and_more'),
    ]

    operations = [
    ]
