# Generated by Django 5.2.6 on 2025-09-22 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_add_certificate_management_fields'),
    ]

    operations = [
    ]
