# Generated by Django 5.2.6 on 2025-09-22 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_add_policies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='issued_by',
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('policy_id', models.AutoField(primary_key=True, serialize=False)),
                ('policy_number', models.CharField(max_length=50, unique=True)),
                ('effective_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('annual_premium', models.DecimalField(decimal_places=2, max_digits=12)),
                ('billing_frequency', models.CharField(choices=[('annual', 'Annual'), ('semi_annual', 'Semi-Annual'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly')], default='annual', max_length=20)),
                ('policy_status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('non_renewed', 'Non-Renewed'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('auto_renewal', models.BooleanField(default=True)),
                ('renewal_notice_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.quote')),
            ],
            options={
                'verbose_name': 'Policy',
                'verbose_name_plural': 'Policies',
                'db_table': 'policies',
            },
        ),
        migrations.CreateModel(
            name='PolicyRenewal',
            fields=[
                ('renewal_id', models.AutoField(primary_key=True, serialize=False)),
                ('renewal_status', models.CharField(choices=[('pending', 'Pending'), ('quoted', 'Quoted'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('non_renewed', 'Non-Renewed')], default='pending', max_length=20)),
                ('renewal_date', models.DateField()),
                ('notice_sent_date', models.DateField(blank=True, null=True)),
                ('response_due_date', models.DateField(blank=True, null=True)),
                ('proposed_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('premium_change_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='applications.policy')),
                ('renewal_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='renewed_from', to='applications.policy')),
                ('renewal_quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.quote')),
            ],
            options={
                'db_table': 'policy_renewals',
            },
        ),
        migrations.CreateModel(
            name='PolicyTransaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('new_business', 'New Business'), ('renewal', 'Renewal'), ('endorsement', 'Endorsement'), ('cancellation', 'Cancellation'), ('reinstatement', 'Reinstatement')], max_length=20)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('effective_date', models.DateField()),
                ('premium_change', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField()),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='applications.policy')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'policy_transactions',
            },
        ),
    ]
