# Generated by Django 5.2.6 on 2025-09-22 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_fix_policy_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialSummary',
            fields=[
                ('summary_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_date', models.DateField()),
                ('total_premium_written', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_premium_collected', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('outstanding_receivables', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_commissions_owed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_commissions_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('active_policies_count', models.IntegerField(default=0)),
                ('new_policies_count', models.IntegerField(default=0)),
                ('renewal_policies_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'financial_summaries',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='BillingSchedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('billing_frequency', models.CharField(choices=[('annual', 'Annual'), ('semi_annual', 'Semi-Annual'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly')], max_length=20)),
                ('total_premium', models.DecimalField(decimal_places=2, max_digits=12)),
                ('installments_count', models.IntegerField()),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('first_payment_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='applications.policy')),
            ],
            options={
                'db_table': 'billing_schedules',
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('commission_id', models.AutoField(primary_key=True, serialize=False)),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_status', models.CharField(choices=[('pending', 'Pending'), ('calculated', 'Calculated'), ('paid', 'Paid'), ('disputed', 'Disputed')], default='pending', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.broker')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.policy')),
            ],
            options={
                'db_table': 'commissions',
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('installment_number', models.IntegerField()),
                ('due_date', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('check', 'Check'), ('ach', 'ACH/Bank Transfer'), ('credit_card', 'Credit Card'), ('wire', 'Wire Transfer'), ('cash', 'Cash')], max_length=20, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.billingschedule')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='applications.policy')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_records',
                'ordering': ['due_date'],
            },
        ),
    ]
