# Generated by Django 5.2.6 on 2025-09-24 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_add_billing_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceTracker',
            fields=[
                ('sequence_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_code', models.CharField(max_length=3, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('last_used_number', models.IntegerField(default=0)),
                ('last_reserved_number', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sequence_trackers',
            },
        ),
        migrations.AddField(
            model_name='policy',
            name='base_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='issued_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='issued_to_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policy',
            name='original_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_renewals', to='applications.policy'),
        ),
        migrations.AddField(
            model_name='policy',
            name='parent_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals_chain', to='applications.policy'),
        ),
        migrations.AddField(
            model_name='policy',
            name='sequence_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='policy',
            name='version_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='document_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='base_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='parent_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='applications.quote'),
        ),
        migrations.AddField(
            model_name='quote',
            name='presented_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='presented_to_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='sequence_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quote',
            name='version_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
