# Generated by Django 5.2.6 on 2025-09-24 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_add_sequence_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='base_number',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='parent_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='applications.application'),
        ),
        migrations.AddField(
            model_name='application',
            name='sequence_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='version_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='base_number',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='base_number',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
