# Generated by Django 5.2.6 on 2025-09-24 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_add_application_numbering_6digit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('template_id', models.AutoField(primary_key=True, serialize=False)),
                ('template_code', models.CharField(max_length=50, unique=True)),
                ('template_name', models.CharField(max_length=200)),
                ('template_type', models.CharField(choices=[('declaration', 'Declaration Page'), ('policy_form', 'Policy Form'), ('endorsement', 'Endorsement'), ('state_form', 'State Mandatory Form'), ('schedule', 'Schedule'), ('notice', 'Notice'), ('certificate', 'Certificate')], max_length=20)),
                ('template_format', models.CharField(choices=[('dynamic', 'Dynamic (Generated)'), ('static', 'Static (PDF/Word)'), ('hybrid', 'Hybrid (Fillable)')], max_length=20)),
                ('applicable_states', models.CharField(blank=True, max_length=500, null=True)),
                ('is_state_mandatory', models.BooleanField(default=False)),
                ('storage_path', models.CharField(blank=True, max_length=500, null=True)),
                ('storage_bucket', models.CharField(default='default', max_length=100)),
                ('html_template', models.TextField(blank=True, null=True)),
                ('merge_fields', models.JSONField(blank=True, default=dict)),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('effective_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('default_sequence', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.product')),
            ],
            options={
                'db_table': 'document_templates',
                'ordering': ['template_type', 'default_sequence', 'template_name'],
            },
        ),
        migrations.CreateModel(
            name='EndorsementDocument',
            fields=[
                ('endorsement_id', models.AutoField(primary_key=True, serialize=False)),
                ('endorsement_number', models.CharField(max_length=50, unique=True)),
                ('endorsement_sequence', models.IntegerField(default=1)),
                ('endorsement_title', models.CharField(max_length=200)),
                ('effective_date', models.DateField()),
                ('document_path', models.CharField(blank=True, max_length=500, null=True)),
                ('document_bucket', models.CharField(default='endorsements', max_length=100)),
                ('endorsement_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsements', to='applications.policy')),
                ('policy_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.policytransaction')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.documenttemplate')),
            ],
            options={
                'db_table': 'endorsement_documents',
                'ordering': ['policy', 'endorsement_sequence'],
            },
        ),
        migrations.CreateModel(
            name='PolicyDocumentPackage',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('package_number', models.CharField(max_length=50, unique=True)),
                ('package_version', models.IntegerField(default=0)),
                ('package_status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('issued', 'Issued'), ('reissued', 'Reissued'), ('superseded', 'Superseded')], default='draft', max_length=20)),
                ('is_current', models.BooleanField(default=True)),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('issued_date', models.DateTimeField(blank=True, null=True)),
                ('combined_pdf_path', models.CharField(blank=True, max_length=500, null=True)),
                ('combined_pdf_bucket', models.CharField(default='policy-packages', max_length=100)),
                ('total_pages', models.IntegerField(default=0)),
                ('file_size', models.BigIntegerField(default=0)),
                ('generation_data', models.JSONField(default=dict)),
                ('state_code', models.CharField(blank=True, max_length=2, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_packages', to='applications.policy')),
            ],
            options={
                'db_table': 'policy_document_packages',
                'ordering': ['-package_version', '-generated_date'],
            },
        ),
        migrations.CreateModel(
            name='DocumentDelivery',
            fields=[
                ('delivery_id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_method', models.CharField(choices=[('email', 'Email'), ('portal', 'Customer Portal'), ('download', 'Direct Download'), ('print', 'Printed')], max_length=20)),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('viewed', 'Viewed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('delivered_date', models.DateTimeField(blank=True, null=True)),
                ('viewed_date', models.DateTimeField(blank=True, null=True)),
                ('portal_access_token', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('portal_access_expires', models.DateTimeField(blank=True, null=True)),
                ('delivery_metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('endorsement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.endorsementdocument')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.policydocumentpackage')),
            ],
            options={
                'db_table': 'document_deliveries',
            },
        ),
        migrations.CreateModel(
            name='DocumentComponent',
            fields=[
                ('component_id', models.AutoField(primary_key=True, serialize=False)),
                ('component_type', models.CharField(max_length=20)),
                ('component_name', models.CharField(max_length=200)),
                ('sequence_order', models.IntegerField()),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('file_bucket', models.CharField(default='policy-components', max_length=100)),
                ('page_count', models.IntegerField(default=0)),
                ('file_size', models.IntegerField(default=0)),
                ('component_status', models.CharField(choices=[('pending', 'Pending Generation'), ('generated', 'Generated'), ('error', 'Generation Error')], default='pending', max_length=20)),
                ('component_data', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('page_numbering', models.CharField(blank=True, max_length=50)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.documenttemplate')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='applications.policydocumentpackage')),
            ],
            options={
                'db_table': 'document_components',
                'ordering': ['package', 'sequence_order'],
            },
        ),
        migrations.AddIndex(
            model_name='documenttemplate',
            index=models.Index(fields=['template_code'], name='document_te_templat_f24cf9_idx'),
        ),
        migrations.AddIndex(
            model_name='documenttemplate',
            index=models.Index(fields=['product', 'template_type'], name='document_te_product_d78c86_idx'),
        ),
        migrations.AddIndex(
            model_name='endorsementdocument',
            index=models.Index(fields=['policy', 'effective_date'], name='endorsement_policy__32928d_idx'),
        ),
        migrations.AddIndex(
            model_name='policydocumentpackage',
            index=models.Index(fields=['policy', 'is_current'], name='policy_docu_policy__157410_idx'),
        ),
        migrations.AddIndex(
            model_name='policydocumentpackage',
            index=models.Index(fields=['package_status', 'generated_date'], name='policy_docu_package_68b331_idx'),
        ),
        migrations.AddIndex(
            model_name='documentdelivery',
            index=models.Index(fields=['delivery_status', 'created_at'], name='document_de_deliver_3baf41_idx'),
        ),
        migrations.AddIndex(
            model_name='documentdelivery',
            index=models.Index(fields=['portal_access_token'], name='document_de_portal__625e02_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcomponent',
            index=models.Index(fields=['package', 'sequence_order'], name='document_co_package_47ac19_idx'),
        ),
    ]
