# Generated by Django 5.2.6 on 2025-09-22 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0006_add_billing_system'),
        ('claims', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('POLICY', 'Policy Document'), ('CERTIFICATE', 'Certificate of Insurance'), ('INVOICE', 'Invoice'), ('RECEIPT', 'Payment Receipt'), ('CLAIM', 'Claim Document'), ('CORRESPONDENCE', 'Correspondence'), ('OTHER', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='client_portal/documents/%Y/%m/')),
                ('is_visible', models.BooleanField(default=True)),
                ('visible_from', models.DateField(blank=True, null=True)),
                ('visible_until', models.DateField(blank=True, null=True)),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.certificate')),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='claims.claim')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_documents', to='applications.company')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.quote')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_date'],
            },
        ),
        migrations.CreateModel(
            name='ClientActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('VIEW_POLICY', 'Viewed Policy'), ('VIEW_CERTIFICATE', 'Viewed Certificate'), ('VIEW_CLAIM', 'Viewed Claim'), ('SUBMIT_CLAIM', 'Submitted Claim'), ('DOWNLOAD_DOCUMENT', 'Downloaded Document'), ('UPDATE_PROFILE', 'Updated Profile'), ('MAKE_PAYMENT', 'Made Payment'), ('PASSWORD_RESET', 'Password Reset')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('session_key', models.CharField(blank=True, max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.certificate')),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='claims.claim')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.quote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_activities', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_portal.clientdocument')),
            ],
            options={
                'verbose_name_plural': 'Client activities',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='ClientMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('status', models.CharField(choices=[('UNREAD', 'Unread'), ('READ', 'Read'), ('REPLIED', 'Replied'), ('CLOSED', 'Closed')], default='UNREAD', max_length=10)),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('read_date', models.DateTimeField(blank=True, null=True)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='claims.claim')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_messages', to='applications.company')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_portal_messages', to=settings.AUTH_USER_MODEL)),
                ('parent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='client_portal.clientmessage')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.quote')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_portal_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_date'],
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('mobile_phone', models.CharField(blank=True, max_length=20)),
                ('receive_emails', models.BooleanField(default=True)),
                ('receive_sms', models.BooleanField(default=False)),
                ('portal_access_enabled', models.BooleanField(default=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_login_date', models.DateTimeField(blank=True, null=True)),
                ('password_reset_token', models.CharField(blank=True, max_length=100)),
                ('password_reset_date', models.DateTimeField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_users', to='applications.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company', 'user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('payment_type', models.CharField(choices=[('PREMIUM', 'Premium Payment'), ('DEDUCTIBLE', 'Deductible'), ('RENEWAL', 'Renewal'), ('ADDITIONAL', 'Additional Premium'), ('OTHER', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('payment_notes', models.TextField(blank=True)),
                ('show_in_portal', models.BooleanField(default=True)),
                ('allow_online_payment', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='applications.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='applications.quote')),
            ],
            options={
                'ordering': ['due_date', '-created_date'],
            },
        ),
    ]
