# Generated by Django 4.2.7 on 2025-09-14 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('generation_job_id', models.AutoField(primary_key=True, serialize=False)),
                ('generator_model_id', models.IntegerField(blank=True, null=True)),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('data_seed_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'generation_job',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('parameter_id', models.AutoField(primary_key=True, serialize=False)),
                ('parameter_name', models.TextField(blank=True, null=True)),
                ('parameter_type_id', models.IntegerField(blank=True, null=True)),
                ('parameter_docs', models.TextField(blank=True, null=True)),
                ('parameter_quote', models.BooleanField(blank=True, null=True)),
                ('parameter_binder', models.BooleanField(blank=True, null=True)),
                ('parameter_policy', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'parameter',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Venture',
            fields=[
                ('venture_id', models.AutoField(primary_key=True, serialize=False)),
                ('venture_name', models.TextField(blank=True, null=True)),
                ('venture_address_1', models.TextField(blank=True, null=True)),
                ('venture_address_2', models.TextField(blank=True, null=True)),
                ('venture_city', models.TextField(blank=True, null=True)),
                ('venture_state', models.TextField(blank=True, null=True)),
                ('venture_zip', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'venture',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmployeeLocation',
            fields=[
                ('employee_location_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_location_name', models.TextField(blank=True, null=True)),
                ('employee_location_address_1', models.TextField(blank=True, null=True)),
                ('employee_location_address_2', models.TextField(blank=True, null=True)),
                ('employee_location_city', models.TextField(blank=True, null=True)),
                ('employee_location_state', models.TextField(blank=True, null=True)),
                ('employee_location_zip', models.TextField(blank=True, null=True)),
                ('venture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.venture')),
            ],
            options={
                'db_table': 'employee_location',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('drive_id', models.AutoField(primary_key=True, serialize=False)),
                ('drive_name', models.TextField(blank=True, null=True)),
                ('venture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.venture')),
            ],
            options={
                'db_table': 'drive',
                'managed': True,
            },
        ),
    ]
