# Generated by Django 4.2.7 on 2025-09-19 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationQuestion',
            fields=[
                ('application_question_id', models.AutoField(primary_key=True, serialize=False)),
                ('custom_question', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'application_question',
            },
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('broker_id', models.AutoField(primary_key=True, serialize=False)),
                ('broker_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'broker',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('cover_id', models.AutoField(primary_key=True, serialize=False)),
                ('cover_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cover',
            },
        ),
        migrations.CreateModel(
            name='Coverage',
            fields=[
                ('coverage_id', models.AutoField(primary_key=True, serialize=False)),
                ('coverage_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'coverage',
            },
        ),
        migrations.CreateModel(
            name='EmployeeContact',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name_first', models.TextField(blank=True, null=True)),
                ('employee_name_last', models.TextField(blank=True, null=True)),
                ('employee_email', models.TextField(blank=True, null=True)),
                ('employee_name_combined', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employee_contact',
            },
        ),
        migrations.CreateModel(
            name='FlowOrigin',
            fields=[
                ('flow_origin_id', models.AutoField(primary_key=True, serialize=False)),
                ('flow_origin_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'flow_origin',
            },
        ),
        migrations.CreateModel(
            name='Limits',
            fields=[
                ('limits_id', models.AutoField(primary_key=True, serialize=False)),
                ('limit_text', models.TextField(blank=True, null=True)),
                ('limit_pc_number', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('limit_ag_number', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.cover')),
            ],
            options={
                'db_table': 'limits',
            },
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('options_id', models.AutoField(primary_key=True, serialize=False)),
                ('option_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'options',
            },
        ),
        migrations.CreateModel(
            name='ParameterType',
            fields=[
                ('parameter_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('parameter_type_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'parameter_type',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('products_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.TextField(blank=True, null=True)),
                ('product_code', models.TextField(blank=True, null=True)),
                ('product_prefix', models.TextField(blank=True, null=True)),
                ('documents_name', models.TextField(blank=True, null=True)),
                ('coverage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.coverage')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('stage_id', models.AutoField(primary_key=True, serialize=False)),
                ('stage_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stage',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.TextField(blank=True, null=True)),
                ('task_description', models.TextField(blank=True, null=True)),
                ('task_display', models.TextField(blank=True, null=True)),
                ('subroutine_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='Venture',
            fields=[
                ('venture_id', models.AutoField(primary_key=True, serialize=False)),
                ('venture_name', models.TextField(blank=True, null=True)),
                ('venture_address_1', models.TextField(blank=True, null=True)),
                ('venture_address_2', models.TextField(blank=True, null=True)),
                ('venture_city', models.TextField(blank=True, null=True)),
                ('venture_state', models.TextField(blank=True, null=True)),
                ('venture_zip', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'venture',
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('workflow_id', models.AutoField(primary_key=True, serialize=False)),
                ('workflow_name', models.TextField(blank=True, null=True)),
                ('workflow_type', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'workflow',
            },
        ),
        migrations.CreateModel(
            name='WorkflowDetail',
            fields=[
                ('workflow_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('workflow_sequence', models.IntegerField(blank=True, null=True)),
                ('man_auto', models.BooleanField(default=False)),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.stage')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.task')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.workflow')),
            ],
            options={
                'db_table': 'workflow_detail',
            },
        ),
        migrations.CreateModel(
            name='Retention',
            fields=[
                ('retention_id', models.AutoField(primary_key=True, serialize=False)),
                ('retention_text', models.TextField(blank=True, null=True)),
                ('retention_pc_number', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('retention_ag_number', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.cover')),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.products')),
            ],
            options={
                'db_table': 'retention',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='venture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.venture'),
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('parameter_id', models.AutoField(primary_key=True, serialize=False)),
                ('parameter_name', models.TextField(blank=True, null=True)),
                ('parameter_docs', models.TextField(blank=True, null=True)),
                ('parameter_quote', models.BooleanField(default=False)),
                ('parameter_binder', models.BooleanField(default=False)),
                ('parameter_policy', models.BooleanField(default=False)),
                ('parameter_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.parametertype')),
            ],
            options={
                'db_table': 'parameter',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orders_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_created', models.TimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.company')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.employeecontact')),
                ('flow_origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.floworigin')),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.products')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.stage')),
                ('venture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.venture')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.workflow')),
                ('workflow_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.workflowdetail')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderOption',
            fields=[
                ('order_option_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_option_include', models.BooleanField(default=False)),
                ('premium', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('bound', models.BooleanField(default=False)),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.cover')),
                ('limits', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.limits')),
                ('options', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.options')),
                ('orders', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.orders')),
                ('retention', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.retention')),
            ],
            options={
                'db_table': 'order_option',
            },
        ),
        migrations.AddField(
            model_name='limits',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.products'),
        ),
        migrations.CreateModel(
            name='EmployeeLocation',
            fields=[
                ('employee_location_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_location_name', models.TextField(blank=True, null=True)),
                ('employee_location_address_1', models.TextField(blank=True, null=True)),
                ('employee_location_address_2', models.TextField(blank=True, null=True)),
                ('employee_location_city', models.TextField(blank=True, null=True)),
                ('employee_location_state', models.TextField(blank=True, null=True)),
                ('employee_location_zip', models.TextField(blank=True, null=True)),
                ('venture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.venture')),
            ],
            options={
                'db_table': 'employee_location',
            },
        ),
        migrations.AddField(
            model_name='employeecontact',
            name='employee_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.employeelocation'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_name', models.TextField(blank=True, null=True)),
                ('document_number', models.TextField(blank=True, null=True)),
                ('default_document', models.BooleanField(default=False)),
                ('document_added', models.TimeField(blank=True, null=True)),
                ('document_expiration', models.TimeField(blank=True, null=True)),
                ('document_prior_version', models.IntegerField(blank=True, null=True)),
                ('document_code', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.products')),
            ],
            options={
                'db_table': 'document',
            },
        ),
        migrations.AddField(
            model_name='cover',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.products'),
        ),
        migrations.CreateModel(
            name='CompanyLocation',
            fields=[
                ('company_location_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_location_address_1', models.TextField(blank=True, null=True)),
                ('company_location_address_2', models.TextField(blank=True, null=True)),
                ('company_location_city', models.TextField(blank=True, null=True)),
                ('company_location_state', models.TextField(blank=True, null=True)),
                ('company_location_zip', models.TextField(blank=True, null=True)),
                ('company_mailing', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.company')),
            ],
            options={
                'db_table': 'company_location',
            },
        ),
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('company_contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_contact_first', models.TextField(blank=True, null=True)),
                ('company_contact_last', models.TextField(blank=True, null=True)),
                ('company_contact_phone', models.TextField(blank=True, null=True)),
                ('company_contact_email', models.TextField(blank=True, null=True)),
                ('company_contact_title', models.TextField(blank=True, null=True)),
                ('company_contact_salutation', models.TextField(blank=True, null=True)),
                ('company_web', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.company')),
            ],
            options={
                'db_table': 'company_contact',
            },
        ),
        migrations.CreateModel(
            name='BrokerLocation',
            fields=[
                ('broker_location_id', models.AutoField(primary_key=True, serialize=False)),
                ('broker_address_1', models.TextField(blank=True, null=True)),
                ('broker_address_2', models.TextField(blank=True, null=True)),
                ('broker_city', models.TextField(blank=True, null=True)),
                ('broker_state_id', models.IntegerField(blank=True, null=True)),
                ('broker_zip', models.TextField(blank=True, null=True)),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.broker')),
            ],
            options={
                'db_table': 'broker_location',
            },
        ),
        migrations.CreateModel(
            name='BrokerContact',
            fields=[
                ('broker_contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('broker_first_name', models.TextField(blank=True, null=True)),
                ('broker_last_name', models.TextField(blank=True, null=True)),
                ('broker_email', models.TextField(blank=True, null=True)),
                ('broker_name_combined', models.TextField(blank=True, null=True)),
                ('broker_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.brokerlocation')),
            ],
            options={
                'db_table': 'broker_contact',
            },
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('application_name', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.products')),
            ],
            options={
                'db_table': 'applications',
            },
        ),
        migrations.CreateModel(
            name='ApplicationResponse',
            fields=[
                ('application_response_id', models.AutoField(primary_key=True, serialize=False)),
                ('response', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.applications')),
                ('application_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.applicationquestion')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.orders')),
            ],
            options={
                'db_table': 'application_response',
            },
        ),
        migrations.AddField(
            model_name='applicationquestion',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.applications'),
        ),
        migrations.AddField(
            model_name='applicationquestion',
            name='parameter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.parameter'),
        ),
    ]
