# Generated by Django 4.2.24 on 2025-09-20 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Skye', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('attachment_id', models.AutoField(primary_key=True, serialize=False)),
                ('attachment_name', models.TextField(blank=True, null=True)),
                ('output_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'attachment',
            },
        ),
        migrations.CreateModel(
            name='AttachmentType',
            fields=[
                ('attachment_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('attachment_type_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'attachment_type',
            },
        ),
        migrations.CreateModel(
            name='DataSeed',
            fields=[
                ('data_seed_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_seed_filename', models.TextField(blank=True, null=True)),
                ('show_seed', models.BooleanField(default=False)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.products')),
            ],
            options={
                'db_table': 'data_seed',
            },
        ),
        migrations.CreateModel(
            name='EmployeeFunction',
            fields=[
                ('employee_function_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_function', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employee_function',
            },
        ),
        migrations.CreateModel(
            name='GenerationLog',
            fields=[
                ('output_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_code', models.TextField(blank=True, null=True)),
                ('output_file_name', models.TextField(blank=True, null=True)),
                ('product', models.TextField(blank=True, null=True)),
                ('output_id_2', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'generation_log',
            },
        ),
        migrations.CreateModel(
            name='GenerationModel',
            fields=[
                ('generation_model_id', models.AutoField(primary_key=True, serialize=False)),
                ('generation_model_name', models.TextField(blank=True, null=True)),
                ('python_exe_file', models.TextField(blank=True, null=True)),
                ('python_file_path', models.TextField(blank=True, null=True)),
                ('jupyter_file_path', models.TextField(blank=True, null=True)),
                ('model_filename', models.TextField(blank=True, null=True)),
                ('model_code', models.TextField(blank=True, null=True)),
                ('py_file', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'generation_model',
            },
        ),
        migrations.CreateModel(
            name='InputOutput',
            fields=[
                ('input_output_id', models.AutoField(primary_key=True, serialize=False)),
                ('input_output_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'input_output',
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('paper_id', models.AutoField(primary_key=True, serialize=False)),
                ('paper_name', models.TextField(blank=True, null=True)),
                ('am_best_rating', models.TextField(blank=True, null=True)),
                ('am_best_financial_size', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'paper',
            },
        ),
        migrations.CreateModel(
            name='TrainingModel',
            fields=[
                ('training_model_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.TextField(blank=True, null=True)),
                ('python_exe_file', models.TextField(blank=True, null=True)),
                ('python_file_path', models.TextField(blank=True, null=True)),
                ('jupyter_file_path', models.TextField(blank=True, null=True)),
                ('model_filename', models.TextField(blank=True, null=True)),
                ('model_code', models.TextField(blank=True, null=True)),
                ('py_file', models.TextField(blank=True, null=True)),
                ('pickle_dump', models.TextField(blank=True, null=True)),
                ('inference_py_file', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'training_model',
            },
        ),
        migrations.CreateModel(
            name='WorkflowStandard',
            fields=[
                ('workflow_standard_id', models.AutoField(primary_key=True, serialize=False)),
                ('workflow_type', models.TextField(blank=True, null=True)),
                ('next_stage_id', models.IntegerField(blank=True, null=True)),
                ('workflow_sequence', models.TextField(blank=True, null=True)),
                ('man_auto', models.IntegerField(blank=True, null=True)),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.stage')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.task')),
            ],
            options={
                'db_table': 'workflow_standard',
            },
        ),
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('training_job_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_set_id', models.TextField(blank=True, null=True)),
                ('pickle_file_name', models.TextField(blank=True, null=True)),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.products')),
                ('training_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.trainingmodel')),
            ],
            options={
                'db_table': 'training_job',
            },
        ),
        migrations.CreateModel(
            name='Sublimit',
            fields=[
                ('sublimit_id', models.AutoField(primary_key=True, serialize=False)),
                ('sublimit_name', models.TextField(blank=True, null=True)),
                ('sublimit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('orders', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.orders')),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.products')),
            ],
            options={
                'db_table': 'sublimit',
            },
        ),
        migrations.CreateModel(
            name='ParameterMap',
            fields=[
                ('parameter_map_id', models.AutoField(primary_key=True, serialize=False)),
                ('console_element', models.BooleanField(default=False)),
                ('quote_item', models.BooleanField(default=False)),
                ('binder_item', models.BooleanField(default=False)),
                ('policy_item', models.BooleanField(default=False)),
                ('parameter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.parameter')),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.products')),
            ],
            options={
                'db_table': 'parameter_map',
            },
        ),
        migrations.CreateModel(
            name='PaperDetail',
            fields=[
                ('paper_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('paper_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.paper')),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.products')),
            ],
            options={
                'db_table': 'paper_detail',
            },
        ),
        migrations.CreateModel(
            name='ModelParameter',
            fields=[
                ('model_parameter_id', models.AutoField(primary_key=True, serialize=False)),
                ('input_output', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.inputoutput')),
                ('parameter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.parameter')),
                ('training_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.trainingjob')),
            ],
            options={
                'db_table': 'model_parameter',
            },
        ),
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('generation_job_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_seed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.dataseed')),
                ('generator_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.generationmodel')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.products')),
            ],
            options={
                'db_table': 'generation_job',
            },
        ),
        migrations.CreateModel(
            name='EmployeeFunctionDetail',
            fields=[
                ('employee_function_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('cloud_name', models.TextField(blank=True, null=True)),
                ('iam', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.employeecontact')),
                ('employee_function', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.employeefunction')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.products')),
            ],
            options={
                'db_table': 'employee_function_detail',
            },
        ),
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('drive_id', models.AutoField(primary_key=True, serialize=False)),
                ('drive_name', models.TextField(blank=True, null=True)),
                ('venture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.venture')),
            ],
            options={
                'db_table': 'drive',
            },
        ),
        migrations.CreateModel(
            name='AttachmentDetail',
            fields=[
                ('attachment_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.attachment')),
                ('attachment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.attachmenttype')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.products')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.task')),
            ],
            options={
                'db_table': 'attachment_detail',
            },
        ),
        migrations.AddField(
            model_name='attachment',
            name='attachment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skye.attachmenttype'),
        ),
    ]
